# User input
# # select ADOM
adom: root  # name of adom; if ADOM's are not in use, specify 'root'

# # specify filepath to MetaVariable Excel file
# file_path: example.xlsx
file_path: path/to/your/file

# # specify which sheet to use
# active_sheet: metavariables  # name of the sheet containing metavariables
active_sheet: null  # specify null to use the active (first) sheet of the Excel file

# # select devices - select the devices to include
# device_list: Nashville_Spoke_01  # include just this device
# device_list:  # include any device with the hostname in list
#   - Nashville_Spoke_01
#   - LasVegas_Spoke_02
device_list: null  # include all devices

# # toggle device negation
negate_devices: false  # set to true to include every device except the one(s) listed in the device_list

# # select MetaVariables - select the MetaVariables to include
# variable_list: inet_a_intf  # include just this MetaVariable
# variable_list:  # include just these MetaVariables
#  - inet1_int
#  - inet1_ip
variable_list: null  # include all MetaVariables

# # toggle MetaVariable negation
negate_variables: false  # set to true to include every MetaVariable except the one(s) listed in the device_list

# # update default values
update_defaults: true  # if set to false, the global values row will be ignored when generating JSON

# # specify filepath to MetaVariable JSON file that will be outputted to/inputted from
json_output_file: output.json  # created when XLSX2JSON.exe is run
json_input_file: metadata_variables.json  # imported from when JSON2XLSX.exe is run

# # add new variable/device to Excel sheet when running main-jsxon2xlsx.py
add_new_vars: false  # set to True to add new variables to your Excel spreadsheet when converting JSON to Excel
add_new_devices: false  # set to True to add new devices to your Excel spreadsheet when converting JSON to Excel
